apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gcp-cloud-run-starter-pipeline
description: main application pipeline
serialPipeline:
  stages:
  - targetId: run-gcp-cloud-run-starter-dev
    profiles: [dev]
    strategy:
      standard:
        verify: true
  - targetId: run-gcp-cloud-run-starter-prod
    profiles: [prod]
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25]
          verify: true
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-gcp-cloud-run-starter-dev
description: Cloud Run development service
run:
  location: projects/gcp-cloud-run-starter/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-gcp-cloud-run-starter-prod
description: Cloud Run production service
run:
  location: projects/gcp-cloud-run-starter/locations/us-central1