apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: deploy-gcp-cloud-run-starter
profiles:
- name: dev
  manifests:
    rawYaml:
    - gcp-cloud-run-starter-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - gcp-cloud-run-starter-prod.yaml
verify:
  - name: alpine-wget
    container:
      name: alpine-wget
      image: alpine:3.15.4
      command: ["/bin/sh"]
      args: ["-c", "wget http://www.google.com"]
deploy:
  cloudrun: {}